name: test
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - "ubuntu-latest"
        - "macos-latest"
        go:
        - "1.16"
        - "1.15"
        - "1.14"
        make_target:
        - "test"
        - "vet"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions
    - name: Set build variables
      run: |
        echo "MAKE_TARGET=${{ matrix.make_target }}" >> $GITHUB_ENV
    - name: Run ${{matrix.make_target}}
      run: |
        make $MAKE_TARGET
